platform :ios, '9.3'
target 'ViroSample' do
  use_frameworks!
  pod 'ViroReact', :path => '../node_modules/react-viro/ios/'
  pod 'ViroKit', :path => '../node_modules/react-viro/ios/dist/ViroRenderer/'
  pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-orientation-locker', :path => '../node_modules/react-native-orientation-locker'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RCTRestart', :path => '../node_modules/react-native-restart'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'RNCMaskedView', :path => '../node_modules/@react-native-community/masked-view'

end
